# keys for json creation
AUDIO_PATH = 'audio_path'
AUDIO_DATA = 'audio_data'
START = 'start'
END = 'end'
DATASETS = 'datasets'
ALIAS = 'alias'

EXAMPLE_ID = 'example_id'
OBSERVATION = 'observation'
TRANSCRIPTION = 'transcription'
ORIGINAL_TRANSCRIPTION = 'original_transcription'
SPEAKER_ID = 'speaker_id'
NUM_SPEAKERS = 'num_speaker'
NOISE = 'noise'

# keys for transformer
OBSERVATION_STFT = 'observation_stft'
OBSERVATION_ABS = 'observation_abs'
ALIGNMENT_ACTIVITY = 'alignment_activity'
ACTIVITY = 'activity'
ACTIVTY = 'activity'
SPEECH_FEATURES = 'speech_features'
SPEECH_SOURCE = 'speech_source'
TARGET_VAD = 'target_vad'
TARGET_TIME_VAD = 'target_time_vad'
NUM_SAMPLES = 'num_samples'
NUM_FRAMES = 'num_frames'